import * as stylex from '@stylexjs/stylex';
import { tokens } from './tokens.stylex';

export const headerStyles = stylex.create({
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: {
      default: '80px',
      '@media (min-width: 1100px)': '90px',
    },
    paddingBlock: {
      default: '24px',
      '@media (min-width: 1100px)': '25px',
    },
    paddingInline: {
      default: '20px',
      '@media (min-width: 1100px)': '100px',
    },
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: {
      default: '#1C1C1C',
      '@media (min-width: 1100px)': tokens.borderSubtle,
    },
  },
  brand: {
    color: tokens.textPrimary,
    fontFamily: tokens.fontMono,
    fontSize: {
      default: '18px',
      '@media (min-width: 1100px)': '24px',
    },
    fontWeight: 700,
    lineHeight: {
      default: '27px',
      '@media (min-width: 1100px)': '36px',
    },
    textDecoration: 'none',
    whiteSpace: 'nowrap',
  },
  desktopGroup: {
    display: {
      default: 'none',
      '@media (min-width: 1100px)': 'contents',
    },
  },
  desktopNavList: {
    display: 'flex',
    alignItems: 'center',
    gap: '24px',
    color: tokens.textSecondary,
    fontFamily: tokens.fontMono,
    fontSize: '16px',
    lineHeight: '24px',
    whiteSpace: 'nowrap',
  },
  desktopNavLink: {
    color: 'inherit',
    textDecoration: 'none',
    transitionProperty: 'color',
    transitionDuration: '160ms',
    ':hover': {
      color: tokens.textPrimary,
    },
  },
  mobileButton: {
    display: {
      default: 'flex',
      '@media (min-width: 1100px)': 'none',
    },
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    padding: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.borderSubtle,
    borderRadius: tokens.radiusControl,
    backgroundColor: 'transparent',
  },
  dialog: {
    position: 'fixed',
    inset: 0,
    zIndex: 100,
    width: '100%',
    maxWidth: 'none',
    height: '100dvh',
    maxHeight: 'none',
    margin: 0,
    padding: 0,
    overflowY: 'auto',
    borderWidth: 0,
    backgroundColor: tokens.surfacePage,
    '::backdrop': {
      backgroundColor: tokens.surfacePage,
    },
  },
  menuSurface: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    width: '100%',
    minHeight: '100dvh',
    backgroundColor: tokens.surfacePage,
  },
  menuTop: {
    display: 'flex',
    flexDirection: 'column',
    gap: '40px',
  },
  menuHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '80px',
    paddingBlock: '24px',
    paddingInline: '20px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#1C1C1C',
  },
  mobileNavigation: {
    paddingInline: '24px',
  },
  mobileNavList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  mobileNavLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    color: tokens.textPrimary,
    textDecoration: 'none',
  },
  mobileNavIndex: {
    flex: '0 0 auto',
    color: tokens.textSecondary,
    fontFamily: tokens.fontMono,
    fontSize: '14px',
    lineHeight: '21px',
  },
  mobileNavLabel: {
    color: tokens.textPrimary,
    fontFamily: tokens.fontSans,
    fontSize: '24px',
    fontWeight: 500,
    lineHeight: '29px',
  },
  menuFooter: {
    display: 'flex',
    flexDirection: 'column',
    gap: '28px',
    paddingInline: '24px',
    paddingBottom: '32px',
  },
  menuDivider: {
    width: '100%',
    height: '1px',
    backgroundColor: tokens.borderFaint,
  },
  menuResume: {
    width: '100%',
    height: '48px',
    paddingBlock: '12px',
    paddingInline: '16px',
  },
  connectBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    alignItems: 'flex-start',
    fontFamily: tokens.fontMono,
  },
  connectLabel: {
    color: tokens.textSecondary,
    fontSize: '12px',
    lineHeight: '18px',
    textTransform: 'uppercase',
  },
  socialList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '16px',
    color: tokens.textPrimary,
    fontSize: '14px',
    lineHeight: '21px',
  },
  availability: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
  },
  availabilityIcon: {
    flex: '0 0 auto',
    width: '10px',
    height: '10px',
  },
  availabilityText: {
    color: tokens.textSecondary,
    fontFamily: tokens.fontMono,
    fontSize: '12px',
    lineHeight: '18px',
  },
});
